### PR TITLE
Add VisuallyHidden component and lib

### PR DESCRIPTION
**Pull request by stevesims**
adds new `VisuallyHidden` component, which styles a span as visually-hidden replicating the most common use of that class within govuk-frontend

adds `visuallyHidden()` and `visuallyHidden.focusable()` to `@govuk-react/lib`, tracking equivalent sass helper in govuk-frontend

**Checklist**:

* [x] Documentation
* [x] Tests
* [x] Ready to be merged

### CODE REVIEW

**Comment by penx** [comment]
Deploy preview for *govuk-react* processing.

Building with commit 737f4e49f6ba2756d8b28bfa0fb3963770e7e288

https://app.netlify.com/sites/govuk-react/deploys/5c7fffe641498200070fddec

**Comment by stevesims** [comment]
This PR raises an interesting question/issue for Chromatic testing: as this component is only visible when the item is focussed/active is it possible to get Chromatic to focus the element before making it's images?

**Comment by penx** [comment]
> is it possible to get Chromatic to focus the element before making it's images?

yes, we can make a story called 'focussed' that renders the React component and, on did moun  (or similar) of a storybook-only React component wrapper, add client side js in the storybook  to focus the element, then if necessary use the `delay` config prop of Chromatic to wait for it to execute:

http://docs.chromaticqa.com/delay

**Comment by penx** [comment]
as discussed earlier, I'd like to see a story that does e.g.
```jsx
<VisuallyComplete as={Button} />
```

**Comment by stevesims** [comment]
Added in new storybook examples as requested

**Comment by stevesims** [comment]
Hmmm - delayed captures in Chromatic do not appear to have worked, so "focused" versions aren't getting grabbed.  Will make some tweaks

**Comment by stevesims** [comment]
Chromatic still isn't managing to capture these stories where the element should be focussed.  Next step would be to attempt to upgrade to Storybook 5 - however we're on the final Storybook 4 release and the documentation implies that the `delay` config should be working, so it may be a different issue.

For now I'm inclined to leave this issue and attempt to engage with the Storybook support folks to see what they have to say.

**Pull request merged**
