### PR TITLE
Update checkbox styles to match govuk-frontend

### PR DESCRIPTION
**Pull request by jsrobertson**
Addresses #496 

**Checklist**:

* [x] Documentation N/A
* [x] Tests
* [x] Ready to be merged 

Updated the following:
- Checkbox dimensions from 38x38 px to 40x40 px.
- Text padding
- Tick positioning and dimensions
- Focus outline to the standard 3px (was 4px)
- Added support for hint text as per https://design-system.service.gov.uk/components/checkboxes/hint/index.html

Before:
screenshot 2019-01-17 at 16 05 11

After:
screenshot 2019-01-17 at 16 04 23

screenshot 2019-01-18 at 09 51 41

### CODE REVIEW

**Comment by penx** [comment]
Deploy preview for *govuk-react* processing.

Built with commit 5d0b5d10369dc61e078ba8b6f492efbb685d8938

https://app.netlify.com/sites/govuk-react/deploys/5c40a67f851abf00077ce522

**Comment by jsrobertson** [comment]
Need to add hints as per https://design-system.service.gov.uk/components/checkboxes/hint/index.html

**Comment by penx** [comment]
Travis build failing due to linting issue:

>>> /home/travis/build/govuk-react/govuk-react/components/checkbox/src/index.js
  140:1  error  Trailing spaces not allowed  no-trailing-spaces

**Comment by jsrobertson** [comment]
Fixed linting error and pushed.

**Comment by penx** [comment]
Again something odd is going on with Chromatic - it says 133 specs unchanged... will look in to it.

**Comment by penx** [comment]
I have been in touch with Chromatic and will wait for them to get back, transcript:

> hi, for some reason changes haven't been flagged on 2 pull requests that were opened yesterday
e.g. on this pull request https://github.com/govuk-react/govuk-react/pull/497
the size of checkboxes were changed
here is the reference image from master
https://www.chromaticqa.com/component?appId=5ad61aab7f00090020dfdba8&name=Form%2FCheckbox&branch=master&buildNumber=543
and here is the different image built for this PR https://www.chromaticqa.com/component?appId=5ad61aab7f00090020dfdba8&name=Form%2FCheckbox&branch=496-update-checkbox-styles&buildNumber=552
however Chromatic reports that there are no changes:
https://www.chromaticqa.com/build?appId=5ad61aab7f00090020dfdba8&number=552

**Comment by penx** [comment]
It looks as though the changes were approved here:

https://www.chromaticqa.com/build?appId=5ad61aab7f00090020dfdba8&number=545

@stevesims says he didn't approve and as far as I know @jsrobertson doesn't have access to approve so I guess we have a problem with changes being auto accepted.

@jsrobertson please can you confirm you didn't approve these yourself?

**Comment by jsrobertson** [comment]
@penx I can confirm that I didn't approve the changes and as you say I'm not sure I have access to do so.

**Comment by penx** [comment]
Chromatic are looking in to this. We can merge if anyone's in a rush, or keep it open a bit longer to aid debugging Chromatic...

**Comment by penx** [comment]
@jsrobertson merged and will be in v0.5.0 shortly, thanks!

**Pull request merged**
