### PR TITLE
Date - per field props (e.g. autocomplete and id)

### LINKED ISSUE #926: DateField Input should allow an id to be specified for each field
DateField Input should allow an id to be specified for each field

This is for compatibility with ErrorSummary guidance:

> When a user has to enter their answer into multiple fields, such as the day, month and year fields in the date input component, link to the first field that contains an error.
> 
> If you do not know which field contains an error, link to the first field.

https://design-system.service.gov.uk/components/error-summary/

### PR DESCRIPTION
**Pull request by domdomegg**
Fixes #926

**Checklist**:

* [x] Documentation
* [x] Tests
* [x] Ready to be merged

## Screenshots

image

image

image

## Also see

- https://design-system.service.gov.uk/components/date-input/#use-the-autocomplete-attribute-for-a-date-of-birth
- https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
- https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose.html

### CODE REVIEW

**Comment by penx** [comment]
I think this also resolves #926?

**Review by penx — APPROVED** [review]

**Comment by domdomegg** [comment]
> I think this also resolves #926?

Yes, I think this resolves #926:

image

(I can add this story to the PR if you want - although it's not too interesting...)

**Comment by penx** [comment]
@domdomegg perhaps the DateWithAutoComplete story should be renamed DateWithPerFieldProps, containing both `id` and `autoComplete`? Although there's nothing _visual_ about either of these so I'm not 100% there's a need for them to be in storybook without an accompanying test...

All good though, I can merge this in as-is if you're happy with it?

Are you hoping I'll do a release of govuk-react with these updates soon? Or was there anything else you were hoping to get in before a release?

**Comment by penx** [comment]
And thanks again for your contribution 🙂

**Comment by domdomegg** [comment]
I've renamed the story and added both `id` and `autoComplete` props :)

> Are you hoping I'll do a release of govuk-react with these updates soon?

I don't have an urgent need for govuk-react to be released soon myself - I'm only using it in a couple projects and these updates are critical to getting them working. But releasing them would help, and also other people might need them more urgently for their services :)

> Or was there anything else you were hoping to get in before a release?

I'd quite like to do two things, but I'm not sure whether I'll actually get around to them soon so I wouldn't block a release on waiting for me :)

The things I'd like to improve are (left comments inside issues for better discoverability):
- Adding a SimpleParagraph (name tbd) component, which is just a paragraph without markdown support (see #503).
- Aligning styles, particularly for links and inputs, with the GOV.UK Design system (see #1071, #76)

> And thanks again for your contribution :slightly_smiling_face:

Glad to help - thank you for such an awesome library, and for being a great owner of it!

**Review by penx — APPROVED** [review]

**Pull request merged**
