### PR TITLE
Switch defaultProps to default args

### PR DESCRIPTION
**Pull request by marksmall**
The `defaultProps` has been deprecated for some time for function components. I have gone through and updated all function components to use Default Parameters instead. You can see the deprecation notice at:

https://github.com/reactjs/rfcs/blob/createlement-rfc/text/0000-create-element-changes.md#deprecate-defaultprops-on-function-components

I have only updated **function components**, while leaving the **Class** and **styled** components as is.

**Checklist**:

* [ ] Documentation
* [ ] Tests
* [ ] Ready to be merged

### CODE REVIEW

**Review by penx — APPROVED** [review]

**Comment by penx** [comment]
3 changes shown up in Chromatic, relating to the Tabs component.

All seem to be the same issue, namely that the "Contents" title is no longer showing:

https://www.chromatic.com/component?appId=5ad61aab7f00090020dfdba8&csfId=tabs&specName=Simple%20With%20Map%20And%20Babel%20S%20Proposed%20Class%20Properties%20Plugin&buildNumber=2257

**Review by penx — CHANGES_REQUESTED** [review]
Issues revealed by Chromatic need addressing

**Comment by penx** [comment]
Just the one issue - thank you very much for the contribution :)

**Comment by marksmall** [comment]
@penx Again, sorry this has taken so long to get back to, but other things have just snowballed. Anyway, I've undone one of the `defaultProps` changes I made, so that should fix the chromatic change, I've not found a way to set default text for the `children` prop any other way. 

This should resolve the change being seen in chromatic tests. I think you, or some other person with higher privileges that I have need to do something before the tests actually run, but if I'm wrong, just let me know what I need to do to push this PR forward.

**Comment by richrace** [comment]
Hello :wave: when will this be merged in as [React 18.3.0](https://github.com/facebook/react/releases/tag/v18.3.0) has turned on warnings about `defaultProps` being deprecated.

Or, what can I do to help to get it over the line?

**Comment by penx** [comment]
@richrace this has stalled because it's waiting for me to figure out what is going on with this eslint rule disable here

https://github.com/govuk-react/govuk-react/pull/1388#discussion_r1412898353

I haven't had time to look in to it, happy to take a recommendation if you have time to look

**Comment by richrace** [comment]
See: https://github.com/govuk-react/govuk-react/pull/1650/commits/aca71a3ccdf42a02250ff8b0791ac0d64c674c56

**Comment by richrace** [comment]
Closed in favour of this: https://github.com/govuk-react/govuk-react/pull/1650

**Pull request closed without merging**
