### PR TITLE
Set component backgrounds to white

### PR DESCRIPTION
**Pull request by gavinorland**
Addresses #461.

**Checklist**:

* [ ] Documentation N/A
* [ ] Tests N/A
* [x] Ready to be merged

### CODE REVIEW

**Comment by penx** [comment]
Deploy preview for *govuk-react* processing.

Built with commit 18beca648d2ca490542c7d0fb19c513c49047db0

https://app.netlify.com/sites/govuk-react/deploys/5c348a842b93c60009909188

**Comment by penx** [comment]
I don't understand the underlying issue:

- unless there is a clear need to divert, we should be mirroring govuk-frontend sass
- it's not intended to use these components on a non white background
- if an application wants to have custom styles, we can make some adjustments to support this, but I am not convinced that setting the background to always be white would help more than hinder custom styles
- is there a screenshot of the current issue?
- can we reflect the issue this is solving in a story in storybook?

**Comment by stevesims** [comment]
In our app we have a light grey background - as checkboxes and radio buttons have no background color set, whereas other `input` elements *do* have a white background color set, they look out of place and wrong.  They are inconsistent with their peers.
This can be seen here: https://codesandbox.io/s/wojk6jwpzl

We could allow a prop to set this color as an alternative.  Re-styling is not an option given how these elements are produced and styled.

The same bug exists in govuk-frontend.  I have not yet filed an issue against them, or raised a PR, mostly because creating an example would take time that I've not had so far.

**Comment by penx** [comment]
ok cool thanks for the demo

- what does govuk-frontend do? Does this issue also exist in govuk-frontend?
- if we do this, I would prefer it was a prop that defaults to white but can be overridden
- there should be a story in storybook showing this (e.g. so it is picked up if it is broken in future)

**Comment by jsrobertson** [comment]
Hi @stevesims @penx.  Just come across this while implementing govuk-react checkbox and radio into our apps.

We also have the checkbox on some non white backgrounds (rightly or wrongly) and have stumbled across this issue.  For now though I've targeted in a hacky CSS file we have to get round the issue.

I agree with @stevesims on:
> if we do this, I would prefer it was a prop that defaults to white but can be overridden

I have also noticed that I think the styles on both the radio and checkbox components are slightly different to the latest govuk-frontend ones so I'm wondering if it's best to have an issue.  Checkboxes are now 40px instead of 38px for instance.

**Comment by stevesims** [comment]
We have some drift from govuk-frontend in all our input stylings, mostly because the majority of these components were produced before govuk-frontend was released and thus were based on earlier GDS styles.

I started to work this week on attempting to address this for the `Input` component, but fell down a rabbit-hole related to typography, which I hope to manage to crawl out of tomorrow.  :grin:

Unfortunately @gavinorland  isn't available to finish off addressing @penx's feedback on this issue right now, so if you fancy tackling it @jsrobertson that would be great and we'd welcome either a different PR or further commits against this PR.

**Comment by penx** [comment]
The intention is to completely match govuk-frontend though, so where we don't match then yes issues/bugs can be raised.

**Comment by nalanirojas25** [comment]
@jsrobertson are you actively working on this issue? I was interested in giving it a shot.

**Pull request closed without merging**
