### PR TITLE
Add Accordion component

### PR DESCRIPTION
**Pull request by dsm23**
https://design-system.service.gov.uk/components/accordion/

component:
accordion

**Checklist**:

* [x] Documentation
* [x] Tests
* [x] Ready to be merged

### CODE REVIEW

**Comment by penx** [comment]
Deploy preview for *govuk-react* processing.

Building with commit c70e075e096cdf7f76a3b31f62050be12409f58e

https://app.netlify.com/sites/govuk-react/deploys/5c8fea4b7b9431000935909b

**Comment by mantcz** [comment]
Hello, can I ask what is the status of this PR?

**Comment by penx** [comment]
@mantcz we need someone to review what @dsm23 has done.

I'm not personally using govuk-react myself but am maintaining it where I can. Unfortunately this PR is quite extensive so I'd be keen for reviews from people who are using govuk-react, especially if they aim to use the accordion component.

The fact that the PR is so extensive makes me worry that a simpler solution may be available.

In general I am keen to have more people as maintainers to help with PR reviews such as this.

@jsrobertson are your team still using govuk-react?

**Comment by penx** [comment]
@harrynorthover perhaps this is something you could look at?

**Comment by penx** [comment]
It looks like there are a lot of changed files unrelated to the PR. Perhaps that's related to the merge I just did (sorry if). Needs someone to check this branch out and clean it up.. perhaps rerun the documentation generator.

**Comment by dsm23** [comment]
The hyperlinks may no longer be compliant to gds styled. I can update this pr after work today

**Comment by marksy** [comment]
Is there any update on this PR? It's been open for over 2 years.

**Comment by penx** [comment]
@marksy I assigned this to release 0.11. It will probably need to be redone at that point.

**Pull request closed without merging**
