### PR TITLE
Bugfix/missing dependencies

### PR DESCRIPTION
**Pull request by marksy**
**Checklist**:
Missing dependencies required to build project.

* [ ] Documentation N/A
* [ ] Tests N/A
* [x] Ready to be merged

### CODE REVIEW

**Comment by penx** [comment]
Deploy preview for *govuk-react* processing.

Building with commit 46fca2e7b1751c0e5b3be245722075a34fa3a604

https://app.netlify.com/sites/govuk-react/deploys/5cc7a0bd600cd600089a902f

**Comment by penx** [comment]
If this was an issue previously why was it not picked up by tests or release process?

Is there a unit test we could add that showed any such issue in future

**Comment by marksy** [comment]
Screen Shot 2019-05-25 at 8 02 17 PM

Dunnos but i had to add these after the regular `npm install`

**Comment by marksy** [comment]
> If this was an issue previously why was it not picked up by tests or release process?
looks like travis pipeline is caching the yarn packages which would create a false positive

> 
> Is there a unit test we could add that showed any such issue in future
you could clean node_modules prior to `yarn` or turn off caching

**Pull request closed without merging**
